name: Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: "."
          output-path: my-app.apk
